image: python:3.8
before_script:
  - apt-get update && apt-get install -y nodejs
stages:
  - test
  - deploy
test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest tests/unit/
deploy_cdk:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y npm
    - npm install -g aws-cdk
  script:
    - pip install -r requirements.txt
    - cdk deploy --all --require-approval never
  only:
    - main
